apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sm-operator
  namespace: bitwarden
spec:
  chart:
    spec:
      chart: sm-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitwarden
  values:
      bwSecretsManagerRefreshInterval: 300
  interval: 5m