apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infrastructure/bitwarden
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s