apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cssebot
  namespace: flux-system
spec:
  interval: 15m
  path: "./k8s/apps/cssebot/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system