apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: bw-cssebot-secret
  namespace: cssebot
spec:
  organizationId: "b2236a8b-2cbd-46d5-a6c6-b32c008aced7"
  secretName: cssebot-secret
  authToken:
    secretName: bw-auth-token
    secretKey: token
  map:
      - bwSecretId: b5a9483e-fcfd-4891-816b-b32d004d0b2c
        secretKeyName: db_url
      - bwSecretId: ea486971-bc62-4f6d-b66e-b32d004cb368
        secretKeyName: discord_token
      - bwSecretId: 9fe9ae8a-3d86-44cd-a5e0-b32d004ceb3c
        secretKeyName: github_token