---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  interval: 1m0s
  url: https://charts.bitwarden.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sm-operator
  namespace: bitwarden
spec:
  chart:
    spec:
      chart: sm-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitwarden
  values:
      bwSecretsManagerRefreshInterval: 300
  interval: 5m
---